import { useState } from "react";
import { Link, useNavigate } from "react-router-dom";
import Swal from "sweetalert2";
import api from "../services/api";
import { useAuth } from "../context/AuthContext";
import { useLanguage } from "../context/LanguageContext";
function Login() {
  const navigate=useNavigate(); const {login}=useAuth(); const {t}=useLanguage(); const [formData,setFormData]=useState({correo:"",password:""}); const [loading,setLoading]=useState(false); const [errors,setErrors]=useState({});
  const submit=async(event)=>{event.preventDefault();const next={};if(!formData.correo.trim())next.correo="Ingresa tu correo electrónico.";if(!formData.password)next.password="Ingresa tu contraseña.";setErrors(next);if(Object.keys(next).length)return;setLoading(true);try{const correo=formData.correo.trim().toLowerCase();const users=await api.get(`/usuarios?correo=${encodeURIComponent(correo)}`);const found=users.find((item)=>item.correo.toLowerCase()===correo&&item.password===formData.password);if(!found){await Swal.fire({icon:"error",title:"No pudimos iniciar sesión",text:"El correo o la contraseña son incorrectos.",confirmButtonColor:"#176a4e"});return;}const sessionUser=login(found);await Swal.fire({icon:"success",title:t("auth.welcome"),text:`${t("auth.loginSuccess")} ${sessionUser.nombre}.`,timer:1400,showConfirmButton:false});const path=sessionUser.rol==="admin"?"/admin":sessionUser.rol==="operador"?"/operador":"/turista";navigate(path,{replace:true});}catch(error){console.error(error);Swal.fire({icon:"error",title:"No se pudo iniciar sesión",text:"Verifica que JSON Server esté ejecutándose.",confirmButtonColor:"#176a4e"});}finally{setLoading(false);}};
  return <main className="auth-page"><section className="auth-card" aria-labelledby="login-title"><div className="auth-header"><p className="section-eyebrow">PURAVIDA TRIPS</p><h1 id="login-title">{t("auth.loginTitle")}</h1><p>{t("auth.loginDescription")}</p></div><form className="auth-form" onSubmit={submit} noValidate><div className="form-field"><label htmlFor="correo">{t("auth.email")}</label><input id="correo" name="correo" type="email" value={formData.correo} onChange={(e)=>setFormData({...formData,correo:e.target.value})} autoComplete="email" aria-invalid={Boolean(errors.correo)}/>{errors.correo&&<span className="form-error">{errors.correo}</span>}</div><div className="form-field"><label htmlFor="password">{t("auth.password")}</label><input id="password" name="password" type="password" value={formData.password} onChange={(e)=>setFormData({...formData,password:e.target.value})} autoComplete="current-password" aria-invalid={Boolean(errors.password)}/>{errors.password&&<span className="form-error">{errors.password}</span>}</div><button className="button button-primary" type="submit" disabled={loading}>{loading?"...":t("auth.loginButton")}</button></form><p className="auth-footer-text">{t("auth.noAccount")} <Link to="/register">{t("auth.register")}</Link></p></section></main>;
}
export default Login;
